# docker-finance | modern accounting for the power-user
#
# Copyright (C) 2021-2026 Aaron Fiore (Founder, Evergreen Crypto LLC)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# docker-finance @DOCKER_FINANCE_VERSION@

#
# Custom (optional) Dockerfile
#

#
# NOTE:
#
#   - Uncomment any block below, as needed
#   - Or add your own custom Dockerfile commands here
#   - This file appends to docker-finance's generated Dockerfile
#

USER root
RUN pacman -Syu --noconfirm

##
## Optional (examples)
##

## Finance-related
#RUN pacman -Syu \
#  calc \
#  --noconfirm --disable-download-timeout

## Text editors
#RUN pacman -Syu \
#  emacs-nox \
#  nano \
#  --noconfirm --disable-download-timeout

## Python
#RUN pacman -Syu \
#  python-pipx \
#  --noconfirm --disable-download-timeout

## Python (requires above): xlsx to csv conversion tool
#USER @DOCKER_FINANCE_USER@
#WORKDIR /home/@DOCKER_FINANCE_USER@
#RUN pipx install xlsx2csv
#USER root

##
## Plugins (dependencies)
##

## libbitcoinkernel (bitcoin)
#RUN pacman -Syu \
#  boost \
#  capnproto \
#  cmake \
#  db \
#  --noconfirm --disable-download-timeout

## Add yours below, as needed



# vim: sw=2 sts=2 si ai et
