# docker-finance | modern accounting for the power-user
#
# Copyright (C) 2021-2024 Aaron Fiore (Founder, Evergreen Crypto LLC)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

#
# 'fetch' module
#

USER root

RUN apt-get install -y \
  composer \
  curl \
  php \
  php-bcmath \
  php-curl \
  php-gmp \
  proxychains4

# Add builder user for `composer`
RUN useradd -m -s /bin/bash -r builder

USER builder
WORKDIR /usr/local/lib/php

RUN composer require ozdemirburak/json-csv
RUN composer require ccxt/ccxt

# vim: sw=2 sts=2 si ai et
