# docker-finance | modern accounting for the power-user
#
# Copyright (C) 2021-2024 Aaron Fiore (Founder, Evergreen Crypto LLC)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

#
# 'root' module
#

USER root

# ROOT.cern dependencies (regardless of building or not)
RUN apt-get install -y \
  binutils \
  cmake \
  dpkg-dev \
  g++ \
  gcc \
  libssl-dev \
  libtbb-dev \
  libx11-dev \
  libxext-dev \
  libxft-dev \
  libxpm-dev \
  python3

# ROOT.cern pre-compiled installation
RUN apt-get install -y curl
WORKDIR /usr/local/src
RUN curl --location -O "https://root.cern/download/root_v6.32.02.Linux-ubuntu24.04-x86_64-gcc13.2.tar.gz"
RUN tar xvzf "root_v6.32.02.Linux-ubuntu24.04-x86_64-gcc13.2.tar.gz"

# ROOT.cern environment
#
# bash_aliases notes:
#
#  - *MUST* source thisroot.sh (from any directory)
#
#  - For `docker-finance version` command:
#
#    - To avoid thisroot.sh error, pushd/popd is required (per thisroot.sh)
#
#    - Although $ROOTSYS will be available during normal operation, it won't
#      be avaialble to `docker-finance version`- so add binary to PATH here.
RUN echo "pushd /usr/local/src/root/bin 1>/dev/null && source \"/usr/local/src/root/bin/thisroot.sh\" && popd 1>/dev/null" >>/etc/bash.bashrc
RUN echo "export PATH=\"\$PATH::/usr/local/src/root/bin\"" >>/etc/bash.bashrc

# docker-finance
USER root
RUN apt-get install -y \
  googletest \
  libbenchmark-dev \
  libbotan-2-dev \
  libcrypto++-dev \
  libsodium-dev

# vim: sw=2 sts=2 si ai et
