#pragma once

#include "AppContext.h"
#include "HtmlHelpers.h"
#include <mutex>
#include <sstream>

inline void registerChartRoutes(httplib::Server& svr, AppContext& ctx)
{
    auto& db = ctx.defaultDb;
    auto& dbMutex = ctx.dbMutex;

    // ========== GET /chart � Interactive visualization ==========
    svr.Get("/chart", [&](const httplib::Request&, httplib::Response& res) {
        std::ostringstream pg;
        pg << "<!DOCTYPE html><html><head><meta charset='utf-8'>"
              "<meta name='viewport' content='width=device-width,initial-scale=1'>"
              "<title>Chart - Quant</title><style>"
              "*{box-sizing:border-box;margin:0;padding:0;}"
              "body{font-family:'Segoe UI',monospace;background:#0b1426;color:#cbd5e1;overflow-x:hidden;}"
              "nav{background:#0f1b2d;padding:10px 20px;border-bottom:1px solid #1a2744;display:flex;gap:8px;flex-wrap:wrap;}"
              "nav a{color:#7b97c4;text-decoration:none;font-size:0.85em;padding:4px 8px;border-radius:4px;}"
              "nav a:hover{background:#132035;}"
              ".wrap{display:flex;height:calc(100vh - 44px);}"
              ".sidebar{width:320px;min-width:320px;background:#0f1b2d;border-right:1px solid #1a2744;"
              "overflow-y:auto;padding:10px;font-size:0.82em;}"
              ".sidebar h3{color:#c9a44a;margin:8px 0 4px 0;font-size:0.9em;border-bottom:1px solid #152238;padding-bottom:3px;}"
              ".sidebar label{display:inline-block;width:100px;color:#64748b;font-size:0.8em;}"
              ".sidebar input,.sidebar select{background:#0b1426;border:1px solid #1a2744;color:#cbd5e1;padding:3px 5px;"
              "border-radius:3px;font-family:inherit;font-size:0.85em;width:100px;margin:1px 0;}"
              ".sidebar input:focus,.sidebar select:focus{border-color:#c9a44a;outline:none;}"
              ".sidebar .row{display:flex;align-items:center;margin:2px 0;}"
              ".canvas-wrap{flex:1;position:relative;overflow:hidden;}"
              "canvas{display:block;width:100%;height:100%;}"
              ".tooltip{position:absolute;background:#0f1b2dee;border:1px solid #1a2744;border-radius:6px;padding:6px 10px;"
              "font-size:0.78em;color:#cbd5e1;pointer-events:none;display:none;white-space:pre;z-index:10;}"
              ".legend{position:absolute;top:8px;right:8px;background:#0f1b2ddd;border:1px solid #1a2744;border-radius:6px;"
              "padding:8px 12px;font-size:0.75em;z-index:5;}"
              ".legend div{display:flex;align-items:center;gap:6px;margin:2px 0;}"
              ".legend span.sw{display:inline-block;width:24px;height:3px;border-radius:1px;}"
              ".tabs{display:flex;gap:0;margin-bottom:8px;}"
              ".tabs button{flex:1;background:#0b1426;border:1px solid #1a2744;color:#64748b;padding:5px;cursor:pointer;"
              "font-family:inherit;font-size:0.8em;border-radius:0;}"
              ".tabs button:first-child{border-radius:4px 0 0 4px;}"
              ".tabs button:last-child{border-radius:0 4px 4px 0;}"
              ".tabs button.active{background:#1e40af;color:#fff;border-color:#1e40af;}"
              ".mode-panel{display:none;}.mode-panel.active{display:block;}"
              ".stats{display:flex;flex-wrap:wrap;gap:4px;margin:6px 0;}"
              ".stats div{background:#0b1426;border:1px solid #152238;border-radius:4px;padding:3px 6px;font-size:0.75em;}"
              ".stats .lbl{color:#64748b;}.stats .val{color:#c9a44a;}"
              "button.action{background:#166534;color:#fff;border:none;padding:4px 10px;border-radius:4px;cursor:pointer;"
              "font-family:inherit;font-size:0.8em;width:100%;margin:4px 0;}"
              "button.action:hover{background:#15803d;}"
              ".filter-row{margin:4px 0;}.filter-row label{width:auto;margin-right:6px;}"
              ".filter-row input[type=checkbox]{width:auto;margin-right:2px;}"
              "</style></head><body>";
        pg << "<nav>"
              "<a href='/'>Dashboard</a><a href='/trades'>Trades</a><a href='/wallet'>Wallet</a>"
              "<a href='/portfolio'>Portfolio</a><a href='/market-entry'>Entry Calc</a>"
              "<a href='/serial-generator'>Serial Gen</a><a href='/exit-strategy'>Exit Calc</a>"
              "<a href='/entry-points'>Entry Points</a><a href='/pending-exits'>Pending Exits</a>"
              "<a href='/pnl' style='color:#22c55e;'>&#9654; P&amp;L</a>"
              "<a href='/chart' style='color:#c9a44a;font-weight:bold;'>&#9733; Chart</a>"
              "</nav>";
        pg << "<div class='wrap'><div class='sidebar' id='sidebar'>"
              "<div class='tabs' id='modeTabs'>"
              "<button class='active' data-mode='portfolio'>Portfolio</button>"
              "<button data-mode='timeline'>Timeline</button>"
              "<button data-mode='entry'>Entry Calc</button>"
              "<button data-mode='serial'>Serial Gen</button>"
              "<button data-mode='chain'>Chain</button></div>";
        // portfolio panel
        pg << "<div class='mode-panel active' id='panel-portfolio'>"
              "<h3>Existing Data</h3>"
              "<button class='action' onclick='loadPortfolio()'>Refresh Data</button>"
              "<div id='portfolio-symbols'></div>"
              "<div class='filter-row' id='portfolio-filters'></div>"
              "<div class='stats' id='portfolio-stats'></div></div>";
        // timeline panel
        pg << "<div class='mode-panel' id='panel-timeline'>"
              "<h3>Trade Timeline</h3>"
              "<p style='color:#64748b;font-size:0.72em;'>Plots all trades over time with TP/SL levels and realized P&amp;L. "
              "Only trades with timestamps are shown. Old trades without timestamps can be edited on the Trades page.</p>"
              "<button class='action' onclick='loadTimeline()'>Refresh Timeline</button>"
              "<div class='filter-row' id='timeline-filters'></div>"
              "<div class='stats' id='timeline-stats'></div>"
              "<div id='timeline-warn' style='display:none;color:#f59e0b;font-size:0.72em;margin-top:6px;'></div></div>";
        // entry calc panel
        pg << "<div class='mode-panel' id='panel-entry'><h3>Market Entry (Live)</h3>"
              "<div class='row'><label>Symbol</label><input id='e_symbol' value='BTC'></div>"
              "<div class='row'><label>Price</label><input id='e_price' type='number' step='any' value='100000'></div>"
              "<div class='row'><label>Quantity</label><input id='e_qty' type='number' step='any' value='1'></div>"
              "<div class='row'><label>Levels</label><input id='e_levels' type='number' value='4'></div>"
              "<div class='row'><label>Risk</label><input id='e_risk' type='number' step='any' value='0.5'></div>"
              "<div class='row'><label>Steepness</label><input id='e_steepness' type='number' step='any' value='6'></div>"
              "<div class='row'><label>Fee Hedging</label><input id='e_feeHedging' type='number' step='any' value='2'></div>"
              "<div class='row'><label>Pump</label><input id='e_pump' type='number' step='any' value='1000'></div>"
              "<div class='row'><label>Symbols</label><input id='e_symCount' type='number' value='1'></div>"
              "<div class='row'><label>Coeff K</label><input id='e_coeffK' type='number' step='any' value='0'></div>"
              "<div class='row'><label>Fee Spread</label><input id='e_feeSpread' type='number' step='any' value='5'></div>"
              "<div class='row'><label>Delta Time</label><input id='e_deltaTime' type='number' step='any' value='1'></div>"
              "<div class='row'><label>Surplus</label><input id='e_surplus' type='number' step='any' value='0.02'></div>"
              "<div class='row'><label>Max Risk</label><input id='e_maxRisk' type='number' step='any' value='0'></div>"
              "<div class='row'><label>Min Risk</label><input id='e_minRisk' type='number' step='any' value='0'></div>"
              "<div class='row'><label>Direction</label><select id='e_isShort'>"
              "<option value='0'>LONG</option><option value='1'>SHORT</option></select></div>"
              "<div class='row'><label>Funding</label><select id='e_fundMode'>"
              "<option value='1'>Pump only</option><option value='2'>Pump+Wallet</option></select></div>"
              "<div class='row'><label>Range Above</label><input id='e_rangeAbove' type='number' step='any' value='0'></div>"
              "<div class='row'><label>Range Below</label><input id='e_rangeBelow' type='number' step='any' value='0'></div>"
              "<h3>Parameter Models</h3>"
              "<div class='row'><label>Name</label><input id='e_modelName' type='text' value=''></div>"
              "<div class='row'><select id='e_modelSelect' style='width:150px;'><option value=''>-- load --</option></select>"
              "<button type='button' class='action' style='width:auto;margin-left:4px;padding:3px 6px;' onclick='loadModel(\"e\")'>Load</button></div>"
              "<div class='row' style='gap:4px;'>"
              "<button type='button' class='action' style='width:auto;background:#1e40af;' onclick='saveModel(\"e\")'>Save</button>"
              "<button type='button' class='action' style='width:auto;background:#991b1b;' onclick='deleteModel(\"e\")'>Delete</button></div>"
              "<div class='stats' id='entry-stats'></div>"
              "<button class='action' id='saveEntryBtn' style='display:none;background:#1e40af;'>Save Entry Points</button></div>";
        // serial gen panel
        pg << "<div class='mode-panel' id='panel-serial'><h3>Serial Gen (Live)</h3>"
              "<div class='row'><label>Symbol</label><input id='s_symbol' value='BTC'></div>"
              "<div class='row'><label>Price</label><input id='s_price' type='number' step='any' value='100000'></div>"
              "<div class='row'><label>Quantity</label><input id='s_qty' type='number' step='any' value='1'></div>"
              "<div class='row'><label>Levels</label><input id='s_levels' type='number' value='4'></div>"
              "<div class='row'><label>Risk</label><input id='s_risk' type='number' step='any' value='0.5'></div>"
              "<div class='row'><label>Steepness</label><input id='s_steepness' type='number' step='any' value='6'></div>"
              "<div class='row'><label>Fee Hedging</label><input id='s_feeHedging' type='number' step='any' value='2'></div>"
              "<div class='row'><label>Pump</label><input id='s_pump' type='number' step='any' value='1000'></div>"
              "<div class='row'><label>Symbols</label><input id='s_symCount' type='number' value='1'></div>"
              "<div class='row'><label>Coeff K</label><input id='s_coeffK' type='number' step='any' value='0'></div>"
              "<div class='row'><label>Fee Spread</label><input id='s_feeSpread' type='number' step='any' value='5'></div>"
              "<div class='row'><label>Delta Time</label><input id='s_deltaTime' type='number' step='any' value='1'></div>"
              "<div class='row'><label>Surplus</label><input id='s_surplus' type='number' step='any' value='0.02'></div>"
              "<div class='row'><label>Max Risk</label><input id='s_maxRisk' type='number' step='any' value='0'></div>"
              "<div class='row'><label>Min Risk</label><input id='s_minRisk' type='number' step='any' value='0'></div>"
              "<div class='row'><label>Direction</label><select id='s_isShort'>"
              "<option value='0'>LONG</option><option value='1'>SHORT</option></select></div>"
              "<div class='row'><label>Funding</label><select id='s_fundMode'>"
              "<option value='1'>Pump only</option><option value='2'>Pump+Wallet</option></select></div>"
              "<div class='row'><label>Stop Losses</label><select id='s_genSL'>"
              "<option value='0'>No</option><option value='1'>Yes</option></select></div>"
              "<div class='row'><label>Range Above</label><input id='s_rangeAbove' type='number' step='any' value='0'></div>"
              "<div class='row'><label>Range Below</label><input id='s_rangeBelow' type='number' step='any' value='0'></div>"
              "<div class='row'><label>DT Count</label><input id='s_dtCount' type='number' value='1' min='0' title='Number of future downturn cycles to pre-fund (0 = disabled)'></div>"
              "<div class='row'><label>SL Fraction</label><input id='s_slFrac' type='number' step='any' value='1' min='0' max='1' title='Fraction of position to sell at SL (0-1)'></div>"
              "<div class='row'><label>SL Hedge</label><input id='s_slHedge' type='number' value='0' min='0' title='Future SL hits to pre-fund via TP inflation'></div>"
              "<div class='row'><label>Fut Fees</label><input id='s_futFees' type='number' value='0' min='0' title='Future chain trades whose fees to pre-hedge'></div>"
              "<h3>Parameter Models</h3>"
              "<div class='row'><label>Name</label><input id='s_modelName' type='text' value=''></div>"
              "<div class='row'><select id='s_modelSelect' style='width:150px;'><option value=''>-- load --</option></select>"
              "<button type='button' class='action' style='width:auto;margin-left:4px;padding:3px 6px;' onclick='loadModel(\"s\")'>Load</button></div>"
              "<div class='row' style='gap:4px;'>"
              "<button type='button' class='action' style='width:auto;background:#1e40af;' onclick='saveModel(\"s\")'>Save</button>"
              "<button type='button' class='action' style='width:auto;background:#991b1b;' onclick='deleteModel(\"s\")'>Delete</button></div>"
              "<div class='stats' id='serial-stats'></div>"
              "<button class='action' id='saveSerialBtn' style='display:none;background:#1e40af;'>Save Entry Points</button>"
              "<h3>TP Heatmap Overlay</h3>"
              "<div style='color:#64748b;font-size:0.72em;margin-bottom:4px;'>"
              "Sweep params as a trellis of small-multiple heatmaps</div>"
              "<div class='row'><label>X Axis</label><select id='h_axisX' style='width:100px;'>"
              "<option value='pump'>Pump</option><option value='qty'>Quantity</option>"
              "<option value='feeSpread' selected>Fee Spread</option><option value='feeHedging'>Fee Hedging</option>"
              "<option value='deltaTime'>Delta Time</option><option value='surplus'>Surplus</option>"
              "<option value='coeffK'>Coeff K</option><option value='symbols'>Symbols</option></select></div>"
              "<div class='row'><label>Y Axis</label><select id='h_axisY' style='width:100px;'>"
              "<option value='pump' selected>Pump</option><option value='qty'>Quantity</option>"
              "<option value='feeSpread'>Fee Spread</option><option value='feeHedging'>Fee Hedging</option>"
              "<option value='deltaTime'>Delta Time</option><option value='surplus'>Surplus</option>"
              "<option value='coeffK'>Coeff K</option><option value='symbols'>Symbols</option></select></div>"
              "<div class='row'><label>Grid Size</label><input id='h_gridSize' type='number' value='14' style='width:60px;'></div>"
              "<div class='row'><label>X Lo</label><input id='h_xLo' type='number' step='any' value='0.1' style='width:60px;'></div>"
              "<div class='row'><label>X Hi</label><input id='h_xHi' type='number' step='any' value='3' style='width:60px;'></div>"
              "<div class='row'><label>Y Lo</label><input id='h_yLo' type='number' step='any' value='0.1' style='width:60px;'></div>"
              "<div class='row'><label>Y Hi</label><input id='h_yHi' type='number' step='any' value='3' style='width:60px;'></div>"
              "<div class='row'><label>Axis 3</label><select id='h_axis3' style='width:70px;'>"
              "<option value='none' selected>None</option><option value='pump'>Pump</option><option value='qty'>Qty</option>"
              "<option value='feeSpread'>FeeSprd</option><option value='feeHedging'>FeeHdg</option>"
              "<option value='deltaTime'>DeltaT</option><option value='surplus'>Surpl</option>"
              "<option value='coeffK'>CoeffK</option><option value='symbols'>Syms</option></select>"
              "<input id='h_z3Steps' type='number' value='3' min='1' max='6' style='width:24px;margin-left:2px;' title='Steps'>"
              "<input id='h_z3Lo' type='number' step='any' value='0.1' style='width:34px;' title='Lo'>"
              "<input id='h_z3Hi' type='number' step='any' value='3' style='width:34px;' title='Hi'></div>"
              "<div class='row'><label>Axis 4</label><select id='h_axis4' style='width:70px;'>"
              "<option value='none' selected>None</option><option value='pump'>Pump</option><option value='qty'>Qty</option>"
              "<option value='feeSpread'>FeeSprd</option><option value='feeHedging'>FeeHdg</option>"
              "<option value='deltaTime'>DeltaT</option><option value='surplus'>Surpl</option>"
              "<option value='coeffK'>CoeffK</option><option value='symbols'>Syms</option></select>"
              "<input id='h_z4Steps' type='number' value='3' min='1' max='6' style='width:24px;margin-left:2px;' title='Steps'>"
              "<input id='h_z4Lo' type='number' step='any' value='0.1' style='width:34px;' title='Lo'>"
              "<input id='h_z4Hi' type='number' step='any' value='3' style='width:34px;' title='Hi'></div>"
              "<div style='color:#475569;font-size:0.68em;margin:2px 0;'>"
              "Base=0 &#x2192; multiplier becomes absolute value</div>"
              "<button class='action' id='hmToggle' style='background:#4338ca;' onclick='toggleHM()'>&#x1F525; Show Heatmap</button>"
              "<div class='stats' id='heatmap-stats'></div></div>";
        // chain panel
        pg << "<div class='mode-panel' id='panel-chain'><h3>Chain Execution</h3>"
              "<p style='color:#64748b;font-size:0.72em;'>"
              "Preview multi-cycle entry &#x2192; exit chains with compounding capital. "
              "Reads Serial Gen parameters for level generation.</p>"
              "<div class='row'><label>Price</label><input id='ch_price' type='number' step='any' value='100000'></div>"
              "<div class='row'><label>Cycles</label><input id='ch_cycles' type='number' value='3' min='1' max='10'></div>"
              "<div class='row'><label>Savings Rate</label><input id='ch_savings' type='number' step='any' value='0.05'></div>"
              "<div class='stats' id='chain-stats'></div>"
              "<div id='chain-details' style='font-size:0.72em;max-height:250px;overflow-y:auto;'></div>"
              "<button class='action' id='chainSaveBtn' style='display:none;background:#166534;' onclick='saveChain()'>Save Chain (All Cycles)</button>"
              "<div style='margin-top:8px;border-top:1px solid #1a2744;padding-top:8px;'>"
              "<h3>Build from Trade</h3>"
              "<p style='color:#64748b;font-size:0.68em;'>Extrapolate a chain from an existing Buy trade.</p>"
              "<div class='row'><label>Trade ID</label><input id='ch_tradeId' type='number' min='1'></div>"
              "<button class='action' style='background:#7c3aed;' onclick='chainFromTrade()'>Extrapolate Chain</button></div>"
              "<div id='chain-exec' style='margin-top:8px;border-top:1px solid #1a2744;padding-top:8px;'>"
              "<h3>Active Chain</h3>"
              "<div class='stats' id='chain-exec-stats'></div>"
              "<div id='chain-exec-entries' style='font-size:0.72em;max-height:150px;overflow-y:auto;'></div>"
              "<button class='action' id='chainAdvBtn' style='display:none;background:#4338ca;' onclick='chainAdvance()'>Advance to Next Cycle</button>"
              "<button class='action' style='background:#991b1b;margin-top:4px;font-size:0.75em;' onclick='chainReset()'>Reset Chain</button>"
              "</div></div>";
        pg << "</div>"; // sidebar
        pg << "<div class='canvas-wrap' id='canvasWrap'>"
              "<canvas id='chart'></canvas>"
              "<canvas id='heatmapCanvas' style='position:absolute;top:0;left:0;width:100%;height:100%;display:none;pointer-events:none;'></canvas>"
              "<div class='tooltip' id='tip'></div>"
              "<div class='tooltip' id='htip'></div>"
              "<div class='legend' id='legend'>"
              "<div><span class='sw' style='background:#60a5fa'></span> Entry Price</div>"
              "<div><span class='sw' style='background:#22c55e'></span> Take Profit</div>"
              "<div><span class='sw' style='background:#ef4444'></span> Stop Loss</div>"
              "<div><span class='sw' style='background:#f59e0b'></span> Break Even</div>"
              "<div><span class='sw' style='background:#eab308'></span> Current Price</div>"
              "<div><span class='sw' style='background:#64748b'></span> Pending Exit</div>"
              "</div></div></div>";
        // JavaScript - split into multiple strings for MSVC
        pg << "<script>\n(function(){\n'use strict';\n";
        pg << "var $=function(id){return document.getElementById(id);};\n"
              "var canvas=$('chart'),ctx=canvas.getContext('2d');\n"
              "var tip=$('tip'),wrap=$('canvasWrap');\n"
              "var W,H,dpr,currentMode='portfolio';\n"
              "var chartData=[],priceMin=0,priceMax=1;\n"
              "var PAD_L=90,PAD_R=30,PAD_T=30,PAD_B=30;\n"
              "var lastEntryResult=null,lastSerialResult=null;\n";
        pg << "function resize(){dpr=window.devicePixelRatio||1;"
              "W=wrap.clientWidth;H=wrap.clientHeight;"
              "canvas.width=W*dpr;canvas.height=H*dpr;"
              "canvas.style.width=W+'px';canvas.style.height=H+'px';"
              "ctx.setTransform(dpr,0,0,dpr,0,0);draw();"
              "if(hmVisible)drawH();}\n"
              "window.addEventListener('resize',resize);\n";
        pg << "function priceToY(p){var r=priceMax-priceMin;if(r<=0)r=1;"
              "return PAD_T+(1-(p-priceMin)/r)*(H-PAD_T-PAD_B);}\n"
              "function yToPrice(y){var r=priceMax-priceMin;if(r<=0)r=1;"
              "return priceMin+(1-(y-PAD_T)/(H-PAD_T-PAD_B))*r;}\n"
              "function fp(p){if(Math.abs(p)>=1)return p.toFixed(2);"
              "if(Math.abs(p)>=0.01)return p.toFixed(4);return p.toFixed(8);}\n";
        // draw function
        pg << "function draw(){ctx.clearRect(0,0,W,H);ctx.fillStyle='#0b1426';ctx.fillRect(0,0,W,H);\n"
              "if(!chartData.length){ctx.fillStyle='#475569';ctx.font='14px monospace';"
              "ctx.textAlign='center';ctx.fillText('Select a mode and load data',W/2,H/2);return;}\n"
              "var prices=chartData.map(function(d){return d.price;}).filter(function(p){return p>0&&isFinite(p);});\n"
              "if(!prices.length)return;\n"
              "var pMin=Math.min.apply(null,prices),pMax=Math.max.apply(null,prices);\n"
              "var pad=(pMax-pMin)*0.1||pMax*0.1||1;priceMin=pMin-pad;priceMax=pMax+pad;\n";
        pg << "var gs=10,gst=(priceMax-priceMin)/gs;\n"
              "ctx.strokeStyle='#152238';ctx.lineWidth=1;ctx.font='10px monospace';ctx.fillStyle='#475569';ctx.textAlign='right';\n"
              "for(var i=0;i<=gs;i++){var p=priceMin+gst*i,y=priceToY(p);"
              "ctx.beginPath();ctx.moveTo(PAD_L,y);ctx.lineTo(W-PAD_R,y);ctx.stroke();"
              "ctx.fillText(fp(p),PAD_L-4,y+3);}\n";
        pg << "var groups={};chartData.forEach(function(d){var k=d.group||'default';"
              "if(!groups[k])groups[k]=[];groups[k].push(d);});\n"
              "var gk=Object.keys(groups),barW=Math.max(20,Math.min(80,(W-PAD_L-PAD_R)/(gk.length+1))),barGap=8;\n";
        pg << "gk.forEach(function(g,gi){var items=groups[g];"
              "var cx=PAD_L+barW/2+gi*(barW+barGap)+barGap;if(cx>W-PAD_R)return;\n"
              "ctx.fillStyle='#64748b';ctx.textAlign='center';ctx.font='10px monospace';ctx.fillText(g,cx,H-8);\n"
              "items.forEach(function(d){var y=priceToY(d.price);if(y<PAD_T||y>H-PAD_B)return;\n"
              "ctx.save();ctx.strokeStyle=d.color;ctx.lineWidth=d.width||2;\n"
              "if(d.dash)ctx.setLineDash(d.dash);else ctx.setLineDash([]);\n"
              "var x1=cx-barW/2+2,x2=cx+barW/2-2;\n"
              "ctx.beginPath();ctx.moveTo(x1,y);ctx.lineTo(x2,y);ctx.stroke();\n"
              "ctx.fillStyle=d.color;ctx.textAlign='left';ctx.font='9px monospace';\n"
              "ctx.fillText(d.shortLabel||d.type,x2+3,y+3);ctx.restore();});\n";
        pg << "var ei=items.find(function(d){return d.type==='Entry';});\n"
              "if(ei&&ei.funding>0){var mf=Math.max.apply(null,chartData.filter(function(d){return d.funding>0;}).map(function(d){return d.funding;}).concat([1]));\n"
              "var maxBH=Math.max(80,(H-PAD_T-PAD_B)*0.18),bh=(ei.funding/mf)*maxBH,ey=priceToY(ei.price);\n"
              "var alpha=(0.08+0.10*(ei.funding/mf)).toFixed(2);\n"
              "ctx.fillStyle='rgba(96,165,250,'+alpha+')';ctx.fillRect(cx-barW/2+2,ey-bh,barW-4,bh);\n"
              "ctx.fillStyle='#60a5facc';ctx.textAlign='center';ctx.font='bold 9px monospace';\n"
              "var pct=ei.fundPct?ei.fundPct.toFixed(1)+'%':'';\n"
              "ctx.fillText(pct,cx,ey-bh-10);\n"
              "ctx.font='8px monospace';ctx.fillStyle='#60a5fa88';\n"
              "ctx.fillText(fp(ei.qty||0)+' qty',cx,ey-bh-1);}});\n";
        pg << "var cp=chartData.find(function(d){return d.type==='Current';});\n"
              "if(cp){var cy=priceToY(cp.price);ctx.save();ctx.strokeStyle='#eab308';ctx.lineWidth=1.5;\n"
              "ctx.setLineDash([8,4]);ctx.beginPath();ctx.moveTo(PAD_L,cy);ctx.lineTo(W-PAD_R,cy);ctx.stroke();\n"
              "ctx.fillStyle='#eab308';ctx.textAlign='left';ctx.font='11px monospace';\n"
              "ctx.fillText('Current: '+fp(cp.price),PAD_L+4,cy-6);ctx.restore();}}\n";
        // tooltip
        pg << "canvas.addEventListener('mousemove',function(e){\n"
              "var r=canvas.getBoundingClientRect(),mx=e.clientX-r.left,my=e.clientY-r.top;\n"
              "var closest=null,minD=999;\n"
              "chartData.forEach(function(d){if(d.type==='Current')return;\n"
              "var dist=Math.abs(priceToY(d.price)-my);if(dist<minD&&dist<12){minD=dist;closest=d;}});\n"
              "if(closest){var ln=closest.label+'\\nPrice: '+fp(closest.price);\n"
              "if(closest.fundPct)ln+='\\nFund: '+closest.fundPct.toFixed(1)+'%';\n"
              "if(closest.qty)ln+='\\nQty: '+fp(closest.qty);\n"
              "if(closest.funding)ln+='\\nFunding: '+fp(closest.funding);\n"
              "if(closest.feeCost)ln+='\\nFee Cost: '+fp(closest.feeCost);\n"
              "tip.textContent=ln;tip.style.display='block';\n"
              "tip.style.left=(mx+14)+'px';tip.style.top=(my-10)+'px';\n"
              "}else{tip.style.display='none';}});\n"
              "canvas.addEventListener('mouseleave',function(){tip.style.display='none';});\n";
        // tabs
        pg << "$('modeTabs').addEventListener('click',function(e){\n"
              "if(e.target.tagName!=='BUTTON')return;\n"
              "document.querySelectorAll('#modeTabs button').forEach(function(b){b.classList.remove('active');});\n"
              "e.target.classList.add('active');\n"
              "document.querySelectorAll('.mode-panel').forEach(function(p){p.classList.remove('active');});\n"
              "currentMode=e.target.dataset.mode;\n"
              "$('panel-'+currentMode).classList.add('active');\n"
              "if(currentMode==='portfolio')loadPortfolio();\n"
              "if(currentMode==='timeline')loadTimeline();\n"
              "if(currentMode==='chain'){calcChain();loadChainExec();}\n"
              "hmVisible=false;hmCanvas.style.display='none';$('hmToggle').textContent='\u{1F525} Show Heatmap';});\n";
        // portfolio
        pg << "var pTrades=[],pEntries=[],pPending=[],pHorizons={},symFilter={};\n"
              "function loadPortfolio(){\n"
              "Promise.all([fetch('/api/trades').then(function(r){return r.json();}),\n"
              "fetch('/api/entry-points').then(function(r){return r.json();}),\n"
              "fetch('/api/pending-exits').then(function(r){return r.json();})])\n"
              ".then(function(arr){pTrades=arr[0];pEntries=arr[1];pPending=arr[2];pHorizons={};\n"
              "var buys=pTrades.filter(function(t){return t.type==='Buy';});\n"
              "var chain=Promise.resolve();\n"
              "buys.forEach(function(t){chain=chain.then(function(){\n"
              "return fetch('/api/horizons?tradeId='+t.id).then(function(r){return r.json();}).then(function(h){\n"
              "if(h.length>0)pHorizons[t.id]=h;});});});\n"
              "chain.then(function(){\n";
        pg << "var syms=[];pTrades.forEach(function(t){if(syms.indexOf(t.symbol)<0)syms.push(t.symbol);});\n"
              "pEntries.forEach(function(e){if(syms.indexOf(e.symbol)<0)syms.push(e.symbol);});\n"
              "var fd=$('portfolio-filters');fd.innerHTML='<h3>Symbols</h3>';\n"
              "syms.forEach(function(s){if(!(s in symFilter))symFilter[s]=true;\n"
              "var lbl=document.createElement('label');lbl.className='filter-row';\n"
              "var cb=document.createElement('input');cb.type='checkbox';cb.checked=symFilter[s];\n"
              "cb.addEventListener('change',function(){symFilter[s]=cb.checked;drawP();});\n"
              "lbl.appendChild(cb);lbl.appendChild(document.createTextNode(' '+s));fd.appendChild(lbl);});\n"
              "var sd=$('portfolio-stats');sd.innerHTML="
              "'<div><span class=lbl>Trades: </span><span class=val>'+buys.length+'</span></div>'+\n"
              "'<div><span class=lbl>Entries: </span><span class=val>'+pEntries.filter(function(e){return !e.traded;}).length+'</span></div>'+\n"
              "'<div><span class=lbl>Pending: </span><span class=val>'+pPending.length+'</span></div>';\n"
              "drawP();});});}\n";
        // drawP
        pg << "function drawP(){chartData=[];\n"
              "var buys=pTrades.filter(function(t){return t.type==='Buy'&&symFilter[t.symbol]!==false;});\n"
              "buys.forEach(function(t){var g='#'+t.id+' '+t.symbol;\n"
              "chartData.push({label:'Entry #'+t.id+' '+t.symbol,price:t.price,color:'#60a5fa',type:'Entry',"
              "group:g,shortLabel:'E',width:2.5,qty:t.remaining});\n"
              "if(t.tpPrice>0)chartData.push({label:'TP #'+t.id,price:t.tpPrice,color:'#22c55e',type:'TP',"
              "group:g,shortLabel:'TP',width:2,dash:[6,3]});\n"
              "if(t.slPrice>0)chartData.push({label:'SL #'+t.id+(t.slActive?' ON':' OFF'),price:t.slPrice,"
              "color:t.slActive?'#ef4444':'#ef444466',type:'SL',group:g,shortLabel:'SL',width:2,"
              "dash:t.slActive?[]:[4,4]});\n"
              "if(pHorizons[t.id])pHorizons[t.id].forEach(function(h){\n"
              "if(h.tpPrice>0)chartData.push({label:'H'+h.index+' TP',price:h.tpPrice,color:'#22c55e88',"
              "type:'HTP',group:g,shortLabel:'H'+h.index,width:1.5,dash:[4,2]});\n"
              "if(h.slPrice>0)chartData.push({label:'H'+h.index+' SL',price:h.slPrice,color:'#ef444488',"
              "type:'HSL',group:g,shortLabel:'H'+h.index,width:1.5,dash:[4,2]});});});\n";
        pg << "pEntries.filter(function(e){return !e.traded&&symFilter[e.symbol]!==false;}).forEach(function(ep){\n"
              "var g='EP#'+ep.id+' '+ep.symbol;\n"
              "chartData.push({label:'EntryPt #'+ep.id+' L'+ep.level,price:ep.entry,color:'#60a5fa',"
              "type:'Entry',group:g,shortLabel:'E',width:2,dash:[8,3],qty:ep.qty,funding:ep.funding||0,"
              "feeCost:(ep.breakEven>0&&ep.entry>0)?(ep.breakEven-ep.entry)*ep.qty:0});\n"
              "if(ep.breakEven>0)chartData.push({label:'BE #'+ep.id,price:ep.breakEven,color:'#f59e0b',"
              "type:'BE',group:g,shortLabel:'BE',width:1.5,dash:[3,3]});\n"
              "if(ep.tp>0)chartData.push({label:'TP #'+ep.id,price:ep.tp,color:'#22c55e',"
              "type:'TP',group:g,shortLabel:'TP',width:1.5,dash:[6,3]});\n"
              "if(ep.sl>0)chartData.push({label:'SL #'+ep.id,price:ep.sl,color:'#ef4444',"
              "type:'SL',group:g,shortLabel:'SL',width:1.5,dash:[6,3]});});\n";
        pg << "pPending.filter(function(pe){return symFilter[pe.symbol]!==false;}).forEach(function(pe){\n"
              "var mt=pTrades.find(function(t){return t.id===pe.tradeId;});\n"
              "var g=mt?('#'+mt.id+' '+mt.symbol):('PE#'+pe.orderId);\n"
              "chartData.push({label:'PendExit #'+pe.orderId+' L'+pe.level,price:pe.trigger,"
              "color:'#64748b',type:'Pend',group:g,shortLabel:'PX',width:1.5,dash:[3,5]});});\n"
              "draw();}\n";
        // timeline
        pg << "var tlTrades=[],tlFilter={},tlHorizons={};\n"
              "function loadTimeline(){\n"
              "fetch('/api/trades').then(function(r){return r.json();}).then(function(trades){\n"
              "var noTs=trades.filter(function(t){return !t.timestamp||t.timestamp<=0;});\n"
              "tlTrades=trades.filter(function(t){return t.timestamp>0;});\n"
              "var w=$('timeline-warn');\n"
              "if(noTs.length>0){w.style.display='block';w.textContent=noTs.length+' trade(s) have no timestamp and are hidden. Edit them on the Trades page to set a date.';}\n"
              "else{w.style.display='none';}\n"
              // load horizons for buy trades
              "tlHorizons={};\n"
              "var buyTs=tlTrades.filter(function(t){return t.type==='Buy';});\n"
              "var chain=Promise.resolve();\n"
              "buyTs.forEach(function(b){chain=chain.then(function(){\n"
              "return fetch('/api/horizons?tradeId='+b.id).then(function(r){return r.json();}).then(function(h){\n"
              "if(h.length>0)tlHorizons[b.id]=h;});});});\n"
              "chain.then(function(){\n"
              "var syms=[];tlTrades.forEach(function(t){if(syms.indexOf(t.symbol)<0)syms.push(t.symbol);});\n"
              "var fd=$('timeline-filters');fd.innerHTML='<h3>Symbols</h3>';\n"
              "syms.forEach(function(s){if(!(s in tlFilter))tlFilter[s]=true;\n"
              "var lbl=document.createElement('label');lbl.className='filter-row';\n"
              "var cb=document.createElement('input');cb.type='checkbox';cb.checked=tlFilter[s];\n"
              "cb.addEventListener('change',function(){tlFilter[s]=cb.checked;drawTL();});\n"
              "lbl.appendChild(cb);lbl.appendChild(document.createTextNode(' '+s));fd.appendChild(lbl);});\n"
              "var buys=tlTrades.filter(function(t){return t.type==='Buy';});\n"
              "var sells=tlTrades.filter(function(t){return t.type==='Sell';});\n"
              "var totPnl=0;sells.forEach(function(s){\n"
              "var par=buys.find(function(b){return b.id===s.parentId;});\n"
              "if(par)totPnl+=(s.price-par.price)*s.qty;});\n"
              "$('timeline-stats').innerHTML="
              "'<div><span class=lbl>Trades: </span><span class=val>'+tlTrades.length+'</span></div>'+\n"
              "'<div><span class=lbl>Buys: </span><span class=val>'+buys.length+'</span></div>'+\n"
              "'<div><span class=lbl>Sells: </span><span class=val>'+sells.length+'</span></div>'+\n"
              "'<div><span class=lbl>P&L: </span><span class=val>'+(totPnl>=0?'+':'')+totPnl.toFixed(4)+'</span></div>';\n"
              "drawTL();});});}\n";
        pg << "function drawTL(){\n"
              "var ft=tlTrades.filter(function(t){return tlFilter[t.symbol]!==false;});\n"
              "if(!ft.length){chartData=[];draw();return;}\n"
              "var buys=ft.filter(function(t){return t.type==='Buy';});\n"
              "var sells=ft.filter(function(t){return t.type==='Sell';});\n"
              "var tsArr=ft.map(function(t){return t.timestamp;});\n"
              "var tMin=Math.min.apply(null,tsArr),tMax=Math.max.apply(null,tsArr);\n"
              "if(tMax<=tMin)tMax=tMin+3600;\n"
              "var prices=ft.map(function(t){return t.price;});\n"
              "buys.forEach(function(b){if(b.tpPrice>0)prices.push(b.tpPrice);if(b.slPrice>0)prices.push(b.slPrice);\n"
              "if(tlHorizons[b.id])tlHorizons[b.id].forEach(function(h){if(h.tpPrice>0)prices.push(h.tpPrice);if(h.slPrice>0)prices.push(h.slPrice);});});\n"
              "var pMin=Math.min.apply(null,prices),pMax=Math.max.apply(null,prices);\n"
              "var pad=(pMax-pMin)*0.1||1;pMin-=pad;pMax+=pad;\n"
              "priceMin=pMin;priceMax=pMax;\n"
              // Build chartData for the bar-mode draw()
              "chartData=[];\n"
              // draw on raw canvas instead
              "ctx.clearRect(0,0,W,H);ctx.fillStyle='#0b1426';ctx.fillRect(0,0,W,H);\n"
              "var tx=function(t){return PAD_L+(t-tMin)/(tMax-tMin)*(W-PAD_L-PAD_R);};\n"
              "var py=function(p){return PAD_T+(1-(p-pMin)/(pMax-pMin))*(H-PAD_T-PAD_B);};\n"
              // grid
              "var gs=8,gst=(pMax-pMin)/gs;\n"
              "ctx.font='10px monospace';ctx.fillStyle='#475569';ctx.textAlign='right';\n"
              "for(var i=0;i<=gs;i++){var v=pMin+gst*i,y=py(v);\n"
              "ctx.strokeStyle='#152238';ctx.lineWidth=1;ctx.beginPath();\n"
              "ctx.moveTo(PAD_L,y);ctx.lineTo(W-PAD_R,y);ctx.stroke();\n"
              "ctx.fillText(fp(v),PAD_L-4,y+3);}\n"
              // time labels
              "var tSteps=Math.min(8,Math.max(3,Math.floor(W/120)));\n"
              "ctx.textAlign='center';ctx.fillStyle='#475569';ctx.font='9px monospace';\n"
              "for(var i=0;i<=tSteps;i++){var t=tMin+(tMax-tMin)*i/tSteps;\n"
              "var d=new Date(t*1000);ctx.fillText(d.toLocaleDateString(),tx(t),H-4);}\n"
              // buy markers (upward triangle) + TP/SL lines
              "buys.forEach(function(b){\n"
              "var x=tx(b.timestamp),y=py(b.price);\n"
              "ctx.fillStyle='#22c55e';ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-6,y+12);ctx.lineTo(x+6,y+12);ctx.closePath();ctx.fill();\n"
              "ctx.fillStyle='#22c55ecc';ctx.font='9px monospace';ctx.textAlign='center';\n"
              "ctx.fillText('#'+b.id+' '+fp(b.price),x,y+24);\n"
              // TP line
              "if(b.tpPrice>0){var ytp=py(b.tpPrice);\n"
              "ctx.save();ctx.strokeStyle='#22c55e66';ctx.lineWidth=1;ctx.setLineDash([6,3]);\n"
              "ctx.beginPath();ctx.moveTo(x,ytp);ctx.lineTo(W-PAD_R,ytp);ctx.stroke();ctx.restore();\n"
              "ctx.fillStyle='#22c55e88';ctx.font='8px monospace';ctx.fillText('TP '+fp(b.tpPrice),x+30,ytp-3);}\n"
              // SL line
              "if(b.slPrice>0){var ysl=py(b.slPrice);\n"
              "ctx.save();ctx.strokeStyle=b.slActive?'#ef444466':'#ef444433';ctx.lineWidth=1;ctx.setLineDash([4,4]);\n"
              "ctx.beginPath();ctx.moveTo(x,ysl);ctx.lineTo(W-PAD_R,ysl);ctx.stroke();ctx.restore();\n"
              "ctx.fillStyle=b.slActive?'#ef444488':'#ef444444';ctx.font='8px monospace';ctx.fillText('SL '+fp(b.slPrice),x+30,ysl+10);}\n"
              // horizon levels for this buy
              "if(tlHorizons[b.id])tlHorizons[b.id].forEach(function(h){\n"
              "if(h.tpPrice>0){var yh=py(h.tpPrice);\n"
              "ctx.save();ctx.strokeStyle='#22c55e33';ctx.lineWidth=1;ctx.setLineDash([3,3]);\n"
              "ctx.beginPath();ctx.moveTo(x,yh);ctx.lineTo(W-PAD_R,yh);ctx.stroke();ctx.restore();\n"
              "ctx.fillStyle='#22c55e55';ctx.font='7px monospace';ctx.fillText('H'+h.index,x+4,yh-2);}\n"
              "if(h.slPrice>0){var yhs=py(h.slPrice);\n"
              "ctx.save();ctx.strokeStyle='#ef444422';ctx.lineWidth=1;ctx.setLineDash([3,3]);\n"
              "ctx.beginPath();ctx.moveTo(x,yhs);ctx.lineTo(W-PAD_R,yhs);ctx.stroke();ctx.restore();\n"
              "ctx.fillStyle='#ef444433';ctx.font='7px monospace';ctx.fillText('H'+h.index,x+4,yhs+8);}});\n"
              "});\n"
              // sell markers (downward triangle) + P&L
              "sells.forEach(function(s){\n"
              "var x=tx(s.timestamp),y=py(s.price);\n"
              "ctx.fillStyle='#ef4444';ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-6,y-12);ctx.lineTo(x+6,y-12);ctx.closePath();ctx.fill();\n"
              "var par=buys.find(function(b){return b.id===s.parentId;});\n"
              "var pnlStr='';\n"
              "if(par){var pnl=(s.price-par.price)*s.qty;pnlStr=' '+(pnl>=0?'+':'')+fp(pnl);\n"
              // draw connecting line from entry to exit
              "ctx.save();ctx.strokeStyle=pnl>=0?'#22c55e22':'#ef444422';ctx.lineWidth=1;\n"
              "ctx.beginPath();ctx.moveTo(tx(par.timestamp),py(par.price));ctx.lineTo(x,y);ctx.stroke();ctx.restore();}\n"
              "ctx.fillStyle='#ef4444cc';ctx.font='9px monospace';ctx.textAlign='center';\n"
              "ctx.fillText(fp(s.price)+pnlStr,x,y-16);});\n"
              // tooltip for timeline
              "canvas.onmousemove=function(ev){\n"
              "var r=canvas.getBoundingClientRect(),mx=ev.clientX-r.left,my=ev.clientY-r.top;\n"
              "if(mx<PAD_L||mx>W-PAD_R||my<PAD_T||my>H-PAD_B){tip.style.display='none';return;}\n"
              "var closest=null,minD=999;\n"
              "ft.forEach(function(t){var dx=Math.abs(tx(t.timestamp)-mx),dy=Math.abs(py(t.price)-my);\n"
              "var d=Math.sqrt(dx*dx+dy*dy);if(d<minD&&d<30){minD=d;closest=t;}});\n"
              "if(closest){\n"
              "var dt=new Date(closest.timestamp*1000);\n"
              "var ln=closest.type+' #'+closest.id+'\\n'+closest.symbol+' @ '+fp(closest.price)+'\\nQty: '+fp(closest.qty)+'\\n'+dt.toLocaleString();\n"
              "if(closest.type==='Buy'){if(closest.tpPrice>0)ln+='\\nTP: '+fp(closest.tpPrice);if(closest.slPrice>0)ln+='\\nSL: '+fp(closest.slPrice)+(closest.slActive?' ON':' OFF');}\n"
              "if(closest.type==='Sell'&&closest.parentId>=0){var par=buys.find(function(b){return b.id===closest.parentId;});\n"
              "if(par){var pnl=(closest.price-par.price)*closest.qty;ln+='\\nP&L: '+(pnl>=0?'+':'')+fp(pnl);}}\n"
              "tip.textContent=ln;tip.style.display='block';\n"
              "var tx2=mx+14;if(tx2+180>W)tx2=mx-180;\n"
              "tip.style.left=tx2+'px';tip.style.top=(my-10)+'px';\n"
              "}else{tip.style.display='none';}};\n"
              "canvas.onmouseleave=function(){tip.style.display='none';};\n"
              "}\n";
        // entry calc
        pg << "var eTimer=null;\n"
              "function setupE(){var ids=['e_symbol','e_price','e_qty','e_levels','e_risk','e_steepness','e_feeHedging','e_pump',"
              "'e_symCount','e_coeffK','e_feeSpread','e_deltaTime','e_surplus','e_maxRisk','e_minRisk','e_isShort','e_fundMode','e_rangeAbove','e_rangeBelow'];\n"
              "ids.forEach(function(id){$(id).addEventListener('input',function(){\n"
              "clearTimeout(eTimer);eTimer=setTimeout(calcE,200);});});}\n";
        pg << "function calcE(){var body=new URLSearchParams({"
              "symbol:$('e_symbol').value,currentPrice:$('e_price').value,"
              "quantity:$('e_qty').value,levels:$('e_levels').value,"
              "risk:$('e_risk').value,steepness:$('e_steepness').value,feeHedgingCoefficient:$('e_feeHedging').value,"
              "portfolioPump:$('e_pump').value,symbolCount:$('e_symCount').value,"
              "coefficientK:$('e_coeffK').value,feeSpread:$('e_feeSpread').value,"
              "deltaTime:$('e_deltaTime').value,surplusRate:$('e_surplus').value,"
              "isShort:$('e_isShort').value,fundMode:$('e_fundMode').value,maxRisk:$('e_maxRisk').value,"
              "minRisk:$('e_minRisk').value,"
              "rangeAbove:$('e_rangeAbove').value,rangeBelow:$('e_rangeBelow').value});\n"
              "fetch('/api/calc/entry',{method:'POST',body:body}).then(function(r){return r.json();}).then(function(d){\n"
              "if(d.error)return;lastEntryResult=d;$('saveEntryBtn').style.display='block';chartData=[];\n"
              "chartData.push({label:'Current',price:d.currentPrice,color:'#eab308',type:'Current',group:'_'});\n"
              "var efs=parseFloat($('e_feeSpread').value)||0,efh=parseFloat($('e_feeHedging').value)||0,"
              "edt=parseFloat($('e_deltaTime').value)||1,efc=efs*efh*edt;\n"
              "$('entry-stats').innerHTML="
              "'<div><span class=lbl>OH: </span><span class=val>'+(d.overhead*100).toFixed(4)+'%</span></div>'+\n"
              "'<div><span class=lbl>Eff: </span><span class=val>'+(d.effective*100).toFixed(4)+'%</span></div>'+\n"
              "'<div><span class=lbl>Lvls: </span><span class=val>'+d.levels.length+'</span></div>'+\n"
              "'<div><span class=lbl>Spread: </span><span class=val>'+fp(efs)+'</span></div>'+\n"
              "'<div><span class=lbl>Hedging: </span><span class=val>'+fp(efh)+'</span></div>'+\n"
              "'<div><span class=lbl>Fee/Trade: </span><span class=val>'+fp(efc)+'</span></div>';\n"
              "d.levels.forEach(function(lv){var g='L'+lv.index;\n"
              "chartData.push({label:'L'+lv.index+' Entry',price:lv.entry,color:'#60a5fa',type:'Entry',"
              "group:g,shortLabel:'E',width:2.5,qty:lv.qty,funding:lv.funding,feeCost:(lv.breakEven-lv.entry)*lv.qty});\n"
              "chartData.push({label:'L'+lv.index+' BE',price:lv.breakEven,color:'#f59e0b',type:'BE',"
              "group:g,shortLabel:'BE',width:1.5,dash:[3,3]});\n"
              "if(lv.tp>0)chartData.push({label:'L'+lv.index+' TP',price:lv.tp,color:'#22c55e',type:'TP',"
              "group:g,shortLabel:'TP',width:2,dash:[6,3]});\n"
              "if(lv.sl>0)chartData.push({label:'L'+lv.index+' SL',price:lv.sl,color:'#ef4444',type:'SL',"
              "group:g,shortLabel:'SL',width:2,dash:[6,3]});});\n"
              "draw();}).catch(function(){});}\n";
        // serial calc
        pg << "var sTimer=null;\n"
              "function setupS(){var ids=['s_symbol','s_price','s_qty','s_levels','s_risk','s_steepness','s_feeHedging','s_pump',"
              "'s_symCount','s_coeffK','s_feeSpread','s_deltaTime','s_surplus','s_maxRisk','s_minRisk','s_isShort','s_fundMode','s_genSL','s_rangeAbove','s_rangeBelow','s_dtCount','s_slFrac','s_slHedge','s_futFees'];\n"
              "ids.forEach(function(id){$(id).addEventListener('input',function(){\n"
              "clearTimeout(sTimer);sTimer=setTimeout(calcS,200);});});}\n";
        pg << "function calcS(){var body=new URLSearchParams({"
              "symbol:$('s_symbol').value,currentPrice:$('s_price').value,"
              "quantity:$('s_qty').value,levels:$('s_levels').value,"
              "risk:$('s_risk').value,steepness:$('s_steepness').value,"
              "feeHedgingCoefficient:$('s_feeHedging').value,portfolioPump:$('s_pump').value,"
              "symbolCount:$('s_symCount').value,coefficientK:$('s_coeffK').value,"
              "feeSpread:$('s_feeSpread').value,deltaTime:$('s_deltaTime').value,"
              "surplusRate:$('s_surplus').value,maxRisk:$('s_maxRisk').value,minRisk:$('s_minRisk').value,isShort:$('s_isShort').value,"
              "fundMode:$('s_fundMode').value,generateStopLosses:$('s_genSL').value,"
              "rangeAbove:$('s_rangeAbove').value,rangeBelow:$('s_rangeBelow').value,"
              "downtrendCount:$('s_dtCount').value,"
              "stopLossFraction:$('s_slFrac').value,stopLossHedgeCount:$('s_slHedge').value,"
              "futureTradeCount:$('s_futFees').value});\n"
              "fetch('/api/calc/serial',{method:'POST',body:body}).then(function(r){return r.json();}).then(function(d){\n"
              "if(d.error)return;lastSerialResult=d;$('saveSerialBtn').style.display='block';chartData=[];\n"
              "chartData.push({label:'Current',price:d.currentPrice,color:'#eab308',type:'Current',group:'_'});\n"
              "var sfs=parseFloat($('s_feeSpread').value)||0,sfh=parseFloat($('s_feeHedging').value)||0,"
              "sdt=parseFloat($('s_deltaTime').value)||1,sfc=sfs*sfh*sdt;\n"
              "$('serial-stats').innerHTML="
              "'<div><span class=lbl>OH: </span><span class=val>'+(d.overhead*100).toFixed(4)+'%</span></div>'+\n"
              "'<div><span class=lbl>Eff: </span><span class=val>'+(d.effective*100).toFixed(4)+'%</span></div>'+\n"
              "'<div><span class=lbl>Lvls: </span><span class=val>'+d.levels.length+'</span></div>'+\n"
              "'<div><span class=lbl>Spread: </span><span class=val>'+fp(sfs)+'</span></div>'+\n"
              "'<div><span class=lbl>Hedging: </span><span class=val>'+fp(sfh)+'</span></div>'+\n"
              "'<div><span class=lbl>Fee/Trade: </span><span class=val>'+fp(sfc)+'</span></div>'+\n"
              "'<div><span class=lbl>DT Buffer: </span><span class=val>'+(d.dtBuffer!=null?d.dtBuffer.toFixed(6)+'x':'1x')+'</span></div>';\n"
              "d.levels.forEach(function(lv){var g='L'+lv.index;\n"
              "chartData.push({label:'L'+lv.index+' Entry',price:lv.entry,color:'#60a5fa',type:'Entry',"
              "group:g,shortLabel:'E',width:2.5,qty:lv.qty,funding:lv.funding,feeCost:(lv.breakEven-lv.entry)*lv.qty});\n"
              "chartData.push({label:'L'+lv.index+' BE',price:lv.breakEven,color:'#f59e0b',type:'BE',"
              "group:g,shortLabel:'BE',width:1.5,dash:[3,3]});\n"
              "if(lv.tp>0)chartData.push({label:'L'+lv.index+' TP',price:lv.tp,color:'#22c55e',type:'TP',"
              "group:g,shortLabel:'TP',width:2,dash:[6,3]});\n"
              "if(lv.sl>0)chartData.push({label:'L'+lv.index+' SL',price:lv.sl,color:'#ef4444',type:'SL',"
              "group:g,shortLabel:'SL',width:2,dash:[6,3]});});\n"
              "draw();}).catch(function(){});}\n";
        // save functions
        pg << "function saveEntry(){\n"
              "if(!lastEntryResult)return;\n"
              "var f=document.createElement('form');f.method='POST';f.action='/execute-entries';\n"
              "function add(n,v){var i=document.createElement('input');i.type='hidden';i.name=n;i.value=v;f.appendChild(i);}\n"
              "add('symbol',$('e_symbol').value);add('currentPrice',$('e_price').value);\n"
              "add('quantity',$('e_qty').value);add('risk',$('e_risk').value);\n"
              "add('isShort',$('e_isShort').value);add('fundMode',$('e_fundMode').value);\n"
              "add('levels',$('e_levels').value);add('steepness',$('e_steepness').value);add('feeHedgingCoefficient',$('e_feeHedging').value);\n"
              "add('portfolioPump',$('e_pump').value);add('symbolCount',$('e_symCount').value);\n"
              "add('coefficientK',$('e_coeffK').value);add('feeSpread',$('e_feeSpread').value);\n"
              "add('deltaTime',$('e_deltaTime').value);add('surplusRate',$('e_surplus').value);\n"
              "add('maxRisk',$('e_maxRisk').value);add('minRisk',$('e_minRisk').value);\n"
              "add('rangeAbove',$('e_rangeAbove').value);add('rangeBelow',$('e_rangeBelow').value);\n"
              "document.body.appendChild(f);f.submit();}\n";
        pg << "function saveSerial(){\n"
              "if(!lastSerialResult)return;var d=lastSerialResult;\n"
              "var f=document.createElement('form');f.method='POST';f.action='/save-serial';\n"
              "function add(n,v){var i=document.createElement('input');i.type='hidden';i.name=n;i.value=v;f.appendChild(i);}\n"
              "add('symbol',$('s_symbol').value);add('isShort',$('s_isShort').value);\n"
              "add('pump',$('s_pump').value);add('entryCount',d.levels.length);\n"
              "d.levels.forEach(function(lv){\n"
              "add('ep_'+lv.index,lv.entry);add('eq_'+lv.index,lv.qty);\n"
              "add('eb_'+lv.index,lv.breakEven);add('ef_'+lv.index,lv.funding);\n"
              "add('eov_'+lv.index,d.effective);add('etp_'+lv.index,lv.tp);\n"
              "add('esl_'+lv.index,lv.sl);});\n"
              "document.body.appendChild(f);f.submit();}\n";
        // param model functions
        pg << "var paramModels=[];\n"
              "function refreshModels(){\n"
              "fetch('/api/param-models').then(function(r){\n"
              "if(!r.ok)throw new Error('HTTP '+r.status);return r.json();}).then(function(arr){\n"
              "paramModels=arr;\n"
              "['e','s'].forEach(function(p){\n"
              "var sel=$(p+'_modelSelect');sel.innerHTML='<option value=\\'\\'>-- load --</option>';\n"
              "arr.forEach(function(m){var o=document.createElement('option');o.value=m.name;o.textContent=m.name;sel.appendChild(o);});\n"
              "});}).catch(function(e){console.warn('refreshModels:',e);});}\n";
        pg << "function saveModel(prefix){\n"
              "try{\n"
              "var name=$(prefix+'_modelName').value.trim();\n"
              "if(!name){alert('Enter a model name');return;}\n"
              "var btn=event&&event.target;if(btn){btn.textContent='Saving...';btn.disabled=true;}\n"
              "var body=new URLSearchParams({\n"
              "name:name,levels:$(prefix+'_levels').value,risk:$(prefix+'_risk').value,\n"
              "steepness:$(prefix+'_steepness').value,feeHedgingCoefficient:$(prefix+'_feeHedging').value,\n"
              "portfolioPump:$(prefix+'_pump').value,symbolCount:$(prefix+'_symCount').value,\n"
              "coefficientK:$(prefix+'_coeffK').value,feeSpread:$(prefix+'_feeSpread').value,\n"
              "deltaTime:$(prefix+'_deltaTime').value,surplusRate:$(prefix+'_surplus').value,\n"
              "maxRisk:$(prefix+'_maxRisk').value,minRisk:$(prefix+'_minRisk').value,\n"
              "isShort:$(prefix+'_isShort').value,\n"
              "fundMode:$(prefix+'_fundMode').value,\n"
              "rangeAbove:$(prefix+'_rangeAbove').value,rangeBelow:$(prefix+'_rangeBelow').value});\n"
              "if(prefix==='s'&&$(prefix+'_genSL')){body.set('generateStopLosses',$(prefix+'_genSL').value);}\n"
              "if(prefix==='s'&&$(prefix+'_slFrac')){body.set('stopLossFraction',$(prefix+'_slFrac').value);}\n"
              "if(prefix==='s'&&$(prefix+'_slHedge')){body.set('stopLossHedgeCount',$(prefix+'_slHedge').value);}\n"
              "if(prefix==='s'&&$(prefix+'_futFees')){body.set('futureTradeCount',$(prefix+'_futFees').value);}\n"
              "fetch('/api/param-models',{method:'POST',\n"
              "headers:{'Content-Type':'application/x-www-form-urlencoded'},\n"
              "body:body.toString()})\n"
              ".then(function(r){if(!r.ok)return r.text().then(function(t){throw new Error('HTTP '+r.status+': '+t);});return r.json();})\n"
              ".then(function(d){if(btn){btn.textContent='Save';btn.disabled=false;}\n"
              "if(d.ok){refreshModels();\n"
              "var sel=$(prefix+'_modelSelect');\n"
              "setTimeout(function(){sel.value=name;},300);\n"
              "}else{alert('Save failed: '+(d.error||'unknown'));}})\n"
              ".catch(function(e){if(btn){btn.textContent='Save';btn.disabled=false;}alert('Save error: '+e);});\n"
              "}catch(ex){alert('saveModel exception: '+ex.message);}}\n";
        pg << "function loadModel(prefix){\n"
              "var name=$(prefix+'_modelSelect').value;\n"
              "if(!name)return;\n"
              "var m=paramModels.find(function(x){return x.name===name;});\n"
              "if(!m)return;\n"
              "$(prefix+'_levels').value=m.levels;\n"
              "$(prefix+'_risk').value=m.risk;\n"
              "$(prefix+'_steepness').value=m.steepness;\n"
              "$(prefix+'_feeHedging').value=m.feeHedgingCoefficient;\n"
              "$(prefix+'_pump').value=m.portfolioPump;\n"
              "$(prefix+'_symCount').value=m.symbolCount;\n"
              "$(prefix+'_coeffK').value=m.coefficientK;\n"
              "$(prefix+'_feeSpread').value=m.feeSpread;\n"
              "$(prefix+'_deltaTime').value=m.deltaTime;\n"
              "$(prefix+'_surplus').value=m.surplusRate;\n"
              "$(prefix+'_maxRisk').value=m.maxRisk;\n"
              "$(prefix+'_minRisk').value=m.minRisk;\n"
              "$(prefix+'_isShort').value=m.isShort?'1':'0';\n"
              "$(prefix+'_fundMode').value=m.fundMode;\n"
              "$(prefix+'_rangeAbove').value=m.rangeAbove;\n"
              "$(prefix+'_rangeBelow').value=m.rangeBelow;\n"
              "if(prefix==='s'&&$(prefix+'_genSL'))$(prefix+'_genSL').value=m.generateStopLosses?'1':'0';\n"
              "if(prefix==='s'&&$(prefix+'_slFrac'))$(prefix+'_slFrac').value=m.stopLossFraction!=null?m.stopLossFraction:1;\n"
              "if(prefix==='s'&&$(prefix+'_slHedge'))$(prefix+'_slHedge').value=m.stopLossHedgeCount||0;\n"
              "if(prefix==='s'&&$(prefix+'_futFees'))$(prefix+'_futFees').value=m.futureTradeCount||0;\n"
              "$(prefix+'_modelName').value=m.name;\n"
              "if(prefix==='e')calcE();else calcS();}\n";
        pg << "function deleteModel(prefix){\n"
              "var name=$(prefix+'_modelName').value.trim()||($(prefix+'_modelSelect').value);\n"
              "if(!name){alert('Enter or select a model name');return;}\n"
              "if(!confirm('Delete model: '+name+'?'))return;\n"
              "fetch('/api/param-models?name='+encodeURIComponent(name),{method:'DELETE'})\n"
              ".then(function(r){if(!r.ok)throw new Error('HTTP '+r.status);return r.json();})\n"
              ".then(function(){$(prefix+'_modelName').value='';refreshModels();})\n"
              ".catch(function(e){alert('Delete error: '+e);});}\n";
        // heatmap (integrated into serial gen)
        pg << "var hmCanvas=$('heatmapCanvas'),hmCtx=hmCanvas.getContext('2d');\n"
              "var hmTip=$('htip'),hmData=null,hmVisible=false,hmTiles=[],hmFlatMode=false,hmBaseline=0;\n";
        pg << "function toggleHM(){\n"
              "hmVisible=!hmVisible;\n"
              "$('hmToggle').textContent=hmVisible?'\\u{1F525} Hide Heatmap':'\\u{1F525} Show Heatmap';\n"
              "if(hmVisible){calcH();}else{hmCanvas.style.display='none';hmCanvas.style.pointerEvents='none';}\n"
              "}\n";
        pg << "function calcH(){\n"
              "var body=new URLSearchParams({"
              "currentPrice:$('s_price').value,"
              "quantity:$('s_qty').value,"
              "portfolioPump:$('s_pump').value,"
              "feeHedgingCoefficient:$('s_feeHedging').value,"
              "symbolCount:$('s_symCount').value,"
              "coefficientK:$('s_coeffK').value,"
              "feeSpread:$('s_feeSpread').value,"
              "deltaTime:$('s_deltaTime').value,"
              "surplusRate:$('s_surplus').value,"
              "gridSize:$('h_gridSize').value,"
              "axisX:$('h_axisX').value,axisY:$('h_axisY').value,"
              "xLo:$('h_xLo').value,xHi:$('h_xHi').value,"
              "yLo:$('h_yLo').value,yHi:$('h_yHi').value,"
              "axis3:$('h_axis3').value,axis4:$('h_axis4').value,"
              "z3Steps:$('h_z3Steps').value,z3Lo:$('h_z3Lo').value,z3Hi:$('h_z3Hi').value,"
              "z4Steps:$('h_z4Steps').value,z4Lo:$('h_z4Lo').value,z4Hi:$('h_z4Hi').value});\n"
              "fetch('/api/calc/heatmap',{method:'POST',body:body})"
              ".then(function(r){return r.json();})"
              ".then(function(d){\n"
              "if(d.error)return;hmData=d;\n"
              "var minEo=Infinity,maxEo=0;\n"
              "d.slices.forEach(function(sl){sl.rows.forEach(function(row){row.forEach(function(c){\n"
              "if(c.eo<minEo)minEo=c.eo;if(c.eo>maxEo)maxEo=c.eo;});});});\n"
              "var flat=(maxEo-minEo)<0.0001;\n"
              "$('heatmap-stats').innerHTML="
              "'<div><span class=lbl>Min OH: </span><span class=val>'+minEo.toFixed(4)+'%</span></div>'+\n"
              "'<div><span class=lbl>Max OH: </span><span class=val>'+maxEo.toFixed(4)+'%</span></div>'+\n"
              "'<div><span class=lbl>Tiles: </span><span class=val>'+d.slices.length+'</span></div>'+\n"
              "'<div><span class=lbl>Grid: </span><span class=val>'+d.gridSize+'\\u00D7'+d.gridSize+'</span></div>'+\n"
              "(flat?'<div style=\"color:#f59e0b;width:100%\">Low variation \\u2014 showing delta from baseline</div>':'');\n"
              "drawH();}).catch(function(e){console.warn('heatmap:',e);});}\n";
        // heatmap color: low overhead = green (easy TP), high overhead = red (hard TP)
        pg << "function eoColor(eo,mn,mx){\n"
              "var t=(mx>mn)?(eo-mn)/(mx-mn):0.5;t=Math.max(0,Math.min(1,t));\n"
              "var r,g,b;\n"
              "if(t<0.5){var s=t*2;r=Math.round(40+s*180);g=Math.round(180-s*80);b=Math.round(80-s*40);}\n"
              "else{var s=(t-0.5)*2;r=Math.round(220+s*35);g=Math.round(100-s*70);b=Math.round(40-s*20);}\n"
              "return 'rgb('+r+','+g+','+b+')';}\n"
              "function fmtD(v){var a=Math.abs(v);"
              "if(a<1e-6)return v.toExponential(2);"
              "if(a<0.01)return v.toFixed(6);"
              "return v.toFixed(4);}\n";
        // drawH � renders single tile or small-multiples trellis
        pg << "function drawH(){\n"
              "if(!hmData||!hmVisible||currentMode!=='serial'){hmCanvas.style.display='none';hmCanvas.style.pointerEvents='none';return;}\n"
              "hmCanvas.style.display='block';hmCanvas.style.pointerEvents='auto';\n"
              "var dpr=window.devicePixelRatio||1;\n"
              "hmCanvas.width=W*dpr;hmCanvas.height=H*dpr;\n"
              "hmCanvas.style.width=W+'px';hmCanvas.style.height=H+'px';\n"
              "hmCtx.setTransform(dpr,0,0,dpr,0,0);\n"
              "hmCtx.clearRect(0,0,W,H);hmCtx.fillStyle='#0b1426';hmCtx.fillRect(0,0,W,H);\n"
              "var d=hmData,N=d.gridSize;\n"
              "var nC=d.z3Steps,nR=d.z4Steps,multi=(nC>1||nR>1);\n"
              "var AN={pump:'Pump',qty:'Qty',feeSpread:'FeeSprd',feeHedging:'FeeHdg',"
              "deltaTime:'DeltaT',surplus:'Surplus',coeffK:'CoeffK',symbols:'Syms',none:''};\n"
              "var xN=AN[d.axisX]||d.axisX,yN=AN[d.axisY]||d.axisY;\n"
              "var a3N=AN[d.axis3]||'',a4N=AN[d.axis4]||'';\n"
              "var xAbs=Math.abs(d.baseX)<1e-12,yAbs=Math.abs(d.baseY)<1e-12;\n"
              "var a3Abs=Math.abs(d.base3)<1e-12,a4Abs=Math.abs(d.base4)<1e-12;\n";
        // global min/max + layout
        pg << "var gMin=Infinity,gMax=0;\n"
              "d.slices.forEach(function(sl){sl.rows.forEach(function(r){r.forEach(function(c){\n"
              "if(c.eo<gMin)gMin=c.eo;if(c.eo>gMax)gMax=c.eo;});});});\n"
              "hmFlatMode=(gMax-gMin)<0.01;hmBaseline=0;\n"
              "if(hmFlatMode){var sum=0,cnt=0;\n"
              "d.slices.forEach(function(sl){sl.rows.forEach(function(r){r.forEach(function(c){sum+=c.eo;cnt++;});});});\n"
              "hmBaseline=cnt>0?sum/cnt:0;gMin=Infinity;gMax=-Infinity;\n"
              "d.slices.forEach(function(sl){sl.rows.forEach(function(r){r.forEach(function(c){var dv=c.eo-hmBaseline;\n"
              "if(dv<gMin)gMin=dv;if(dv>gMax)gMax=dv;});});});\n"
              "var mxA=Math.max(Math.abs(gMin),Math.abs(gMax),1e-10);gMin=-mxA;gMax=mxA;}\n"
              "var chH=nC>1?16:0,rhW=nR>1?52:0;\n"
              "var P={l:(multi?28:55)+rhW,r:55,t:26+chH,b:multi?28:45};\n"
              "var gap=multi?5:0;\n"
              "var aW=W-P.l-P.r,aH=H-P.t-P.b;\n"
              "var tW=(aW-(nC-1)*gap)/nC,tH=(aH-(nR-1)*gap)/nR;\n"
              "hmTiles=[];\n";
        // render each slice tile
        pg << "d.slices.forEach(function(sl,si){\n"
              "var c3=si%nC,r4=Math.floor(si/nC);\n"
              "var tx=P.l+c3*(tW+gap),ty=P.t+r4*(tH+gap);\n"
              "var cw=tW/N,ch=tH/N;\n"
              "hmTiles.push({x:tx,y:ty,w:tW,h:tH,si:si,cw:cw,ch:ch});\n"
              "if(multi){hmCtx.strokeStyle='#1a2744';hmCtx.lineWidth=0.5;hmCtx.strokeRect(tx,ty,tW,tH);}\n"
              "for(var yi=0;yi<N;yi++){var row=sl.rows[N-1-yi];\n"
              "for(var xi=0;xi<N;xi++){\n"
              "var val=hmFlatMode?(row[xi].eo-hmBaseline):row[xi].eo;\n"
              "hmCtx.fillStyle=eoColor(val,gMin,gMax);\n"
              "hmCtx.globalAlpha=0.82;\n"
              "hmCtx.fillRect(tx+xi*cw,ty+yi*ch,cw-(multi?0.3:0.8),ch-(multi?0.3:0.8));\n"
              "hmCtx.globalAlpha=1.0;\n"
              "if(!multi&&cw>30&&ch>18){\n"
              "hmCtx.fillStyle='#fff';hmCtx.font='bold 9px monospace';hmCtx.textAlign='center';\n"
              "hmCtx.fillText(hmFlatMode?((val>=0?'+':'')+fmtD(val)+'%'):(val.toFixed(2)+'%'),tx+xi*cw+cw/2,ty+yi*ch+ch/2+3);}}}\n"
              "if(r4===0&&nC>1){hmCtx.fillStyle='#c9a44a';hmCtx.font='bold 8px monospace';hmCtx.textAlign='center';\n"
              "hmCtx.fillText(a3N+'='+(a3Abs?sl.z3v.toFixed(1):sl.z3m.toFixed(1)+'x'),tx+tW/2,ty-3);}\n"
              "if(c3===0&&nR>1){hmCtx.fillStyle='#c9a44a';hmCtx.font='bold 8px monospace';hmCtx.textAlign='right';\n"
              "hmCtx.fillText(a4N+'='+(a4Abs?sl.z4v.toFixed(1):sl.z4m.toFixed(1)+'x'),tx-4,ty+tH/2+3);}\n"
              "});\n";
        // axis ticks
        pg << "hmCtx.fillStyle='#64748b';hmCtx.font=(multi?'7':'9')+'px monospace';\n"
              "var nt=multi?2:Math.min(N,6);\n"
              // x ticks (bottom row)
              "hmCtx.textAlign='center';\n"
              "for(var c3=0;c3<nC;c3++){var tx=P.l+c3*(tW+gap),bty=P.t+(nR-1)*(tH+gap)+tH;\n"
              "for(var ti=0;ti<nt;ti++){var xi=Math.round(ti*(N-1)/Math.max(1,nt-1));\n"
              "var xm=d.xLo+(d.xHi-d.xLo)*(N>1?xi/(N-1):0);\n"
              "hmCtx.fillText(xAbs?xm.toFixed(1):xm.toFixed(1)+'x',tx+xi*(tW/N)+(tW/N)/2,bty+(multi?8:12));}}\n"
              // y ticks (leftmost column)
              "hmCtx.textAlign='right';\n"
              "for(var r4=0;r4<nR;r4++){var ty=P.t+r4*(tH+gap);\n"
              "for(var ti=0;ti<nt;ti++){var yi=Math.round(ti*(N-1)/Math.max(1,nt-1));\n"
              "var ym=d.yLo+(d.yHi-d.yLo)*(N>1?(N-1-yi)/(N-1):0);\n"
              "hmCtx.fillText(yAbs?ym.toFixed(1):ym.toFixed(1)+'x',P.l-3,ty+yi*(tH/N)+(tH/N)/2+3);}}\n";
        // axis labels + title + legend
        pg << "hmCtx.fillStyle='#cbd5e1';hmCtx.font='9px monospace';hmCtx.textAlign='center';\n"
              "hmCtx.fillText('\\u2190 '+xN+(xAbs?' (abs)':'')+' \\u2192',W/2,H-3);\n"
              "hmCtx.save();hmCtx.translate(10,H/2);hmCtx.rotate(-Math.PI/2);\n"
              "hmCtx.fillText('\\u2190 '+yN+(yAbs?' (abs)':'')+' \\u2192',0,0);hmCtx.restore();\n"
              "hmCtx.textAlign='center';hmCtx.font='bold 11px monospace';hmCtx.fillStyle='#c9a44a';\n"
              "var ttl=hmFlatMode?('OH \\u0394 from '+hmBaseline.toFixed(2)+'%: '+xN+' vs '+yN):('Eff OH: '+xN+' vs '+yN);\n"
              "if(d.axis3!=='none')ttl+=' | '+a3N;\n"
              "if(d.axis4!=='none')ttl+=' \\u00D7 '+a4N;\n"
              "hmCtx.fillText(ttl,W/2,13);\n"
              "var lx=W-P.r+8,ly=P.t,lh=H-P.t-P.b;\n"
              "for(var i=0;i<lh;i++){hmCtx.fillStyle=eoColor(gMin+(i/lh)*(gMax-gMin),gMin,gMax);hmCtx.fillRect(lx,ly+i,12,1);}\n"
              "hmCtx.fillStyle='#cbd5e1';hmCtx.font='7px monospace';hmCtx.textAlign='left';\n"
              "hmCtx.fillText((hmFlatMode?(gMin>=0?'+':'')+fmtD(gMin):gMin.toFixed(2))+'%',lx+14,ly+7);\n"
              "hmCtx.fillText((hmFlatMode?(gMax>=0?'+':'')+fmtD(gMax):gMax.toFixed(2))+'%',lx+14,ly+lh);\n"
              "hmCtx.fillText(hmFlatMode?'better':'easy',lx+14,ly+17);hmCtx.fillText(hmFlatMode?'worse':'hard',lx+14,ly+lh-8);\n";
        // crosshair (single tile only)
        pg << "if(!multi&&!xAbs&&!yAbs&&hmTiles.length){\n"
              "var cx1=(d.xHi>d.xLo)?(1-d.xLo)/(d.xHi-d.xLo):0.5;\n"
              "var cy1=(d.yHi>d.yLo)?(1-d.yLo)/(d.yHi-d.yLo):0.5;\n"
              "if(cx1>=0&&cx1<=1&&cy1>=0&&cy1<=1){\n"
              "var t0=hmTiles[0],crX=t0.x+cx1*t0.w,crY=t0.y+(1-cy1)*t0.h;\n"
              "hmCtx.save();hmCtx.strokeStyle='#c9a44a';hmCtx.lineWidth=1.5;hmCtx.setLineDash([6,4]);\n"
              "hmCtx.beginPath();hmCtx.moveTo(crX,t0.y);hmCtx.lineTo(crX,t0.y+t0.h);hmCtx.stroke();\n"
              "hmCtx.beginPath();hmCtx.moveTo(t0.x,crY);hmCtx.lineTo(t0.x+t0.w,crY);hmCtx.stroke();\n"
              "hmCtx.setLineDash([]);hmCtx.fillStyle='#c9a44a';hmCtx.beginPath();\n"
              "hmCtx.arc(crX,crY,4,0,Math.PI*2);hmCtx.fill();\n"
              "hmCtx.font='bold 9px monospace';hmCtx.textAlign='left';\n"
              "hmCtx.fillText('1x,1x',crX+6,crY-6);hmCtx.restore();}}\n"
              // TP markers
              "if(lastSerialResult&&lastSerialResult.levels){\n"
              "hmCtx.font='bold 8px monospace';hmCtx.textAlign='right';\n"
              "lastSerialResult.levels.forEach(function(lv){\n"
              "if(lv.tp<=0||lv.entry<=0)return;hmCtx.fillStyle='#22c55e';\n"
              "hmCtx.fillText('L'+lv.index+': '+((lv.tp-lv.entry)/lv.entry*100).toFixed(1)+'%',W-P.r-2,P.t+10+lv.index*10);});}\n"
              "}\n";
        // trellis-aware tooltip
        pg << "hmCanvas.addEventListener('mousemove',function(e){\n"
              "if(!hmData||!hmVisible||currentMode!=='serial'||!hmTiles){hmTip.style.display='none';return;}\n"
              "var r=hmCanvas.getBoundingClientRect(),mx=e.clientX-r.left,my=e.clientY-r.top;\n"
              "var d=hmData,N=d.gridSize,tile=null;\n"
              "for(var i=0;i<hmTiles.length;i++){var t=hmTiles[i];\n"
              "if(mx>=t.x&&mx<t.x+t.w&&my>=t.y&&my<t.y+t.h){tile=t;break;}}\n"
              "if(!tile){hmTip.style.display='none';return;}\n"
              "var xi=Math.floor((mx-tile.x)/tile.cw),yi=Math.floor((my-tile.y)/tile.ch);\n"
              "if(xi<0||xi>=N||yi<0||yi>=N){hmTip.style.display='none';return;}\n"
              "var sl=d.slices[tile.si],c=sl.rows[N-1-yi][xi];\n"
              "var fmt=function(b,m,v){return Math.abs(b)<1e-12?v.toFixed(4):(m.toFixed(2)+'x = '+v.toFixed(4));};\n"
              "var txt=d.axisX+': '+fmt(d.baseX,c.xm,c.xv)+'\\n'+d.axisY+': '+fmt(d.baseY,c.ym,c.yv);\n"
              "if(d.axis3!=='none')txt+='\\n'+d.axis3+': '+fmt(d.base3,sl.z3m,sl.z3v);\n"
              "if(d.axis4!=='none')txt+='\\n'+d.axis4+': '+fmt(d.base4,sl.z4m,sl.z4v);\n"
              "txt+='\\nEff OH: '+c.eo.toFixed(4)+'%';\n"
              "if(hmFlatMode){var dv=c.eo-hmBaseline;txt+='\\n\\u0394: '+(dv>=0?'+':'')+fmtD(dv)+'%';}\n"
              "txt+='\\nRaw OH: '+fmtD(c.oh)+'%';\n"
              "hmTip.textContent=txt;hmTip.style.display='block';\n"
              "hmTip.style.left=(mx+14)+'px';hmTip.style.top=(my-10)+'px';});\n"
              "hmCanvas.addEventListener('mouseleave',function(){hmTip.style.display='none';});\n";
        // chain execution — live multi-cycle preview + execution tracking
        pg << "var chTimer=null,lastChainResult=null;\n"
              "function setupCh(){var ids=['ch_price','ch_cycles','ch_savings'];\n"
              "ids.forEach(function(id){var el=$(id);if(el)el.addEventListener('input',function(){\n"
              "clearTimeout(chTimer);chTimer=setTimeout(calcChain,300);});});\n"
              // also react to serial gen param changes
              "var sids=['s_qty','s_levels','s_risk','s_steepness','s_feeHedging','s_pump',\n"
              "'s_symCount','s_coeffK','s_feeSpread','s_deltaTime','s_surplus',\n"
              "'s_maxRisk','s_minRisk','s_isShort','s_fundMode','s_genSL',\n"
              "'s_rangeAbove','s_rangeBelow','s_dtCount'];\n"
              "sids.forEach(function(id){var el=$(id);if(el)el.addEventListener('input',function(){\n"
              "if(currentMode==='chain'){clearTimeout(chTimer);chTimer=setTimeout(calcChain,400);}});});}\n";
        pg << "function calcChain(){\n"
              "var price=parseFloat($('ch_price').value);\n"
              "if(!price||price<=0){chartData=[];draw();return;}\n"
              "var body=new URLSearchParams({\n"
              "currentPrice:price,\n"
              "quantity:$('s_qty').value||'1',levels:$('s_levels').value||'4',\n"
              "risk:$('s_risk').value||'0.5',steepness:$('s_steepness').value||'6',\n"
              "feeHedgingCoefficient:$('s_feeHedging').value||'1',\n"
              "portfolioPump:$('s_pump').value||'0',\n"
              "symbolCount:$('s_symCount').value||'1',\n"
              "coefficientK:$('s_coeffK').value||'0',feeSpread:$('s_feeSpread').value||'0',\n"
              "deltaTime:$('s_deltaTime').value||'1',surplusRate:$('s_surplus').value||'0.02',\n"
              "maxRisk:$('s_maxRisk').value||'0',minRisk:$('s_minRisk').value||'0',\n"
              "isShort:$('s_isShort').value||'0',fundMode:$('s_fundMode').value||'1',\n"
              "generateStopLosses:$('s_genSL').value||'0',\n"
              "rangeAbove:$('s_rangeAbove').value||'0',rangeBelow:$('s_rangeBelow').value||'0',\n"
              "downtrendCount:$('s_dtCount').value||'1',\n"
              "stopLossFraction:$('s_slFrac').value||'1',stopLossHedgeCount:$('s_slHedge').value||'0',\n"
              "futureTradeCount:$('s_futFees').value||'0',\n"
              "chainCycles:$('ch_cycles').value||'3',\n"
              "savingsRate:$('ch_savings').value||'0.05'});\n"
              "fetch('/api/calc/chain',{method:'POST',body:body})\n"
              ".then(function(r){return r.json();}).then(function(d){\n"
              "if(d.error){chartData=[];draw();return;}\n"
              "lastChainResult=d;$('chainSaveBtn').style.display='block';\n"
              "drawChainChart(d);showChainStats(d);\n"
              "}).catch(function(e){console.warn('calcChain:',e);});}\n";
        pg << "function drawChainChart(d){chartData=[];\n"
              "chartData.push({label:'Current',price:d.currentPrice,color:'#eab308',type:'Current',group:'_'});\n"
              "var cols=['#60a5fa','#c9a44a','#a78bfa','#f472b6','#34d399','#fb923c','#38bdf8','#e879f9','#4ade80','#f87171'];\n"
              "d.cycles.forEach(function(c,ci){\n"
              "var col=cols[ci%cols.length];\n"
              "c.levels.forEach(function(lv){\n"
              "var g='C'+ci+'L'+lv.index;\n"
              "chartData.push({label:'C'+ci+' L'+lv.index+' Entry',price:lv.entry,\n"
              "color:col,type:'Entry',group:g,shortLabel:'E',width:2.5,\n"
              "qty:lv.qty,funding:lv.funding,fundPct:lv.fundPct,\n"
              "feeCost:(lv.breakEven-lv.entry)*lv.qty,dash:ci>0?[6,3]:[]});\n"
              "chartData.push({label:'C'+ci+' BE',price:lv.breakEven,\n"
              "color:'#f59e0b',type:'BE',group:g,shortLabel:'BE',width:1,dash:[3,3]});\n"
              "if(lv.tp>0)chartData.push({label:'C'+ci+' TP',price:lv.tp,\n"
              "color:'#22c55e',type:'TP',group:g,shortLabel:'TP',width:2,dash:[6,3]});\n"
              "if(lv.sl>0)chartData.push({label:'C'+ci+' SL',price:lv.sl,\n"
              "color:'#ef4444',type:'SL',group:g,shortLabel:'SL',width:2,dash:[6,3]});});});\n"
              "draw();}\n";
        pg << "function showChainStats(d){\n"
              "var tp=0,ts=0;d.cycles.forEach(function(c){tp+=c.profit;ts+=c.savings;});\n"
              "var c0=d.cycles[0],cN=d.cycles[d.cycles.length-1];\n"
              "$('chain-stats').innerHTML=\n"
              "'<div><span class=lbl>Cycles: </span><span class=val>'+d.cycles.length+'</span></div>'+\n"
              "'<div><span class=lbl>Start: </span><span class=val>'+fp(c0.capital)+'</span></div>'+\n"
              "'<div><span class=lbl>End: </span><span class=val>'+fp(cN.capitalAfter)+'</span></div>'+\n"
              "'<div><span class=lbl>Profit: </span><span class=val>'+fp(tp)+'</span></div>'+\n"
              "'<div><span class=lbl>Saved: </span><span class=val>'+fp(ts)+'</span></div>'+\n"
              "'<div><span class=lbl>Growth: </span><span class=val>'+(c0.capital>0?((cN.capitalAfter/c0.capital-1)*100).toFixed(2)+'%':'N/A')+'</span></div>';\n"
              "var html='';var cols=['#60a5fa','#c9a44a','#a78bfa','#f472b6','#34d399'];\n"
              "d.cycles.forEach(function(c,ci){\n"
              "html+='<div style=\"margin:3px 0;padding:4px;background:#0b1426;border-radius:3px;border-left:3px solid '+cols[ci%5]+'\">';\n"
              "html+='<b>Cycle '+ci+'</b> '+fp(c.capital)+' &#x2192; '+fp(c.capitalAfter);\n"
              "html+=' <span class=\"buy\">+'+fp(c.profit)+'</span>';\n"
              "if(c.savings>0)html+=' saved: '+fp(c.savings);\n"
              "html+='</div>';});\n"
              "$('chain-details').innerHTML=html;}\n";
        pg << "function saveChain(){\n"
              "if(!lastChainResult||!lastChainResult.cycles||!lastChainResult.cycles.length)return;\n"
              "if(!confirm('Save entire chain ('+lastChainResult.cycles.length+' cycles, all entry points)? This starts chain tracking.'))return;\n"
              "var btn=$('chainSaveBtn');btn.textContent='Saving...';btn.disabled=true;\n"
              "var body=new URLSearchParams({\n"
              "symbol:$('s_symbol').value||'BTC',\n"
              "currentPrice:$('ch_price').value,\n"
              "savingsRate:$('ch_savings').value||'0.05',\n"
              "chainCycles:$('ch_cycles').value||'3',\n"
              "quantity:$('s_qty').value||'1',levels:$('s_levels').value||'4',\n"
              "risk:$('s_risk').value||'0.5',steepness:$('s_steepness').value||'6',\n"
              "feeHedgingCoefficient:$('s_feeHedging').value||'1',\n"
              "portfolioPump:$('s_pump').value||'0',\n"
              "symbolCount:$('s_symCount').value||'1',\n"
              "coefficientK:$('s_coeffK').value||'0',feeSpread:$('s_feeSpread').value||'0',\n"
              "deltaTime:$('s_deltaTime').value||'1',surplusRate:$('s_surplus').value||'0.02',\n"
              "maxRisk:$('s_maxRisk').value||'0',minRisk:$('s_minRisk').value||'0',\n"
              "isShort:$('s_isShort').value||'0',fundMode:$('s_fundMode').value||'1',\n"
              "generateStopLosses:$('s_genSL').value||'0',\n"
              "rangeAbove:$('s_rangeAbove').value||'0',rangeBelow:$('s_rangeBelow').value||'0',\n"
              "downtrendCount:$('s_dtCount').value||'1'});\n"
              "fetch('/api/chain/save-all',{method:'POST',body:body})\n"
              ".then(function(r){return r.json();}).then(function(d){\n"
              "btn.textContent='Save Chain (All Cycles)';btn.disabled=false;\n"
              "if(d.error){alert(d.error);return;}\n"
              "alert(d.entries+' entries saved across '+d.cycles+' cycles. Chain tracking active.');\n"
              "loadChainExec();\n"
              "}).catch(function(e){btn.textContent='Save Chain (All Cycles)';btn.disabled=false;alert('Error: '+e);});}\n";
        // chain execution tracking
        pg << "function loadChainExec(){\n"
              "fetch('/api/chain/status').then(function(r){return r.json();}).then(function(d){\n"
              "if(!d.active){\n"
              "$('chain-exec-stats').innerHTML='<div><span class=lbl>No active chain. Save entries then start via /api/chain/start.</span></div>';\n"
              "$('chain-exec-entries').innerHTML='';$('chainAdvBtn').style.display='none';return;}\n"
              "$('chain-exec-stats').innerHTML=\n"
              "'<div><span class=lbl>Symbol: </span><span class=val>'+d.symbol+'</span></div>'+\n"
              "'<div><span class=lbl>Cycle: </span><span class=val>'+d.cycle+'</span></div>'+\n"
              "'<div><span class=lbl>Done: </span><span class=val>'+(d.completionPct||0).toFixed(1)+'%</span></div>'+\n"
              "'<div><span class=lbl>P&L: </span><span class=val>'+fp(d.cycleRealizedPnl)+'</span></div>'+\n"
              "'<div><span class=lbl>Savings: </span><span class=val>'+fp(d.totalSavings)+'</span></div>';\n"
              "$('chainAdvBtn').style.display=d.cycleComplete?'block':'none';\n"
              "var el=$('chain-exec-entries');if(d.cycleEntries&&d.cycleEntries.length){\n"
              "var html='';d.cycleEntries.forEach(function(e){\n"
              "var st=e.traded?(e.fullySold?'SOLD':'OPEN'):'PENDING';\n"
              "var cl=e.traded?(e.fullySold?'sell':'buy'):'';\n"
              "html+='<div style=\"margin:1px 0;\">EP#'+e.id+' '+fp(e.entry)+' <span class=\"'+cl+'\">'+st+'</span></div>';});\n"
              "el.innerHTML=html;}else{el.innerHTML='';}\n"
              "}).catch(function(){});}\n";
        pg << "function chainAdvance(){\n"
              "var price=parseFloat($('ch_price').value);\n"
              "if(!price||price<=0){alert('Enter current price in the Price field');return;}\n"
              "var body=new URLSearchParams({\n"
              "currentPrice:price,\n"
              "quantity:$('s_qty').value||'1',levels:$('s_levels').value||'4',\n"
              "risk:$('s_risk').value||'0.5',steepness:$('s_steepness').value||'6',\n"
              "feeHedgingCoefficient:$('s_feeHedging').value||'1',\n"
              "symbolCount:$('s_symCount').value||'1',\n"
              "coefficientK:$('s_coeffK').value||'0',feeSpread:$('s_feeSpread').value||'0',\n"
              "deltaTime:$('s_deltaTime').value||'1',surplusRate:$('s_surplus').value||'0.02',\n"
              "maxRisk:$('s_maxRisk').value||'0',minRisk:$('s_minRisk').value||'0',\n"
              "isShort:$('s_isShort').value||'0',\n"
              "generateStopLosses:$('s_genSL').value||'0',\n"
              "rangeAbove:$('s_rangeAbove').value||'0',rangeBelow:$('s_rangeBelow').value||'0',\n"
              "downtrendCount:$('s_dtCount').value||'1'});\n"
              "fetch('/api/chain/advance',{method:'POST',body:body})\n"
              ".then(function(r){return r.json();}).then(function(d){\n"
              "if(d.error){alert(d.error);return;}\n"
              "loadChainExec();calcChain();\n"
              "}).catch(function(e){alert('Error: '+e);});}\n";
        pg << "function chainReset(){\n"
              "if(!confirm('Reset chain tracking? Existing entries/trades are kept.'))return;\n"
              "fetch('/api/chain/reset',{method:'POST'})\n"
              ".then(function(r){return r.json();}).then(function(){\n"
              "loadChainExec();\n"
              "}).catch(function(e){alert('Error: '+e);});}\n";
        pg << "function chainFromTrade(){\n"
              "var tid=parseInt($('ch_tradeId').value);\n"
              "if(!tid||tid<=0){alert('Enter a trade ID');return;}\n"
              "if(!confirm('Build chain from trade #'+tid+'? This replaces any active chain.'))return;\n"
              "var body=new URLSearchParams({\n"
              "tradeId:tid,savingsRate:$('ch_savings').value||'0.05',\n"
              "chainCycles:$('ch_cycles').value||'3',\n"
              "quantity:$('s_qty').value||'1',levels:$('s_levels').value||'4',\n"
              "risk:$('s_risk').value||'0.5',steepness:$('s_steepness').value||'6',\n"
              "feeHedgingCoefficient:$('s_feeHedging').value||'1',\n"
              "symbolCount:$('s_symCount').value||'1',\n"
              "coefficientK:$('s_coeffK').value||'0',feeSpread:$('s_feeSpread').value||'0',\n"
              "deltaTime:$('s_deltaTime').value||'1',surplusRate:$('s_surplus').value||'0.02',\n"
              "maxRisk:$('s_maxRisk').value||'0',minRisk:$('s_minRisk').value||'0',\n"
              "isShort:$('s_isShort').value||'0',\n"
              "generateStopLosses:$('s_genSL').value||'0',\n"
              "rangeAbove:$('s_rangeAbove').value||'0',rangeBelow:$('s_rangeBelow').value||'0',\n"
              "downtrendCount:$('s_dtCount').value||'1'});\n"
              "fetch('/api/chain/from-trade',{method:'POST',body:body})\n"
              ".then(function(r){return r.json();}).then(function(d){\n"
              "if(d.error){alert(d.error);return;}\n"
              "$('ch_price').value=d.tradePrice;\n"
              "alert('Chain built from trade #'+d.tradeId+': '+d.entries+' entries across '+d.cycles+' cycles. Cost: '+fp(d.tradeCost));\n"
              "loadChainExec();calcChain();\n"
              "}).catch(function(e){alert('Error: '+e);});}\n";
        // expose functions used by inline onclick handlers to global scope
        pg << "window.loadPortfolio=loadPortfolio;window.loadTimeline=loadTimeline;\n"
              "window.calcE=calcE;window.calcS=calcS;\n"
              "window.saveModel=saveModel;window.loadModel=loadModel;window.deleteModel=deleteModel;\n"
              "window.toggleHM=toggleHM;window.calcH=calcH;\n"
              "window.calcChain=calcChain;window.saveChain=saveChain;\n"
              "window.loadChainExec=loadChainExec;window.chainAdvance=chainAdvance;window.chainReset=chainReset;\n"
              "window.chainFromTrade=chainFromTrade;\n";
        // init
        pg << "$('saveEntryBtn').addEventListener('click',saveEntry);\n"
              "$('saveSerialBtn').addEventListener('click',saveSerial);\n"
              "setupE();setupS();setupCh();resize();loadPortfolio();refreshModels();\n"
              "})();\n</script></body></html>";
        res.set_content(pg.str(), "text/html");
    });
}
