# docker-finance | modern accounting for the power-user
#
# Copyright (C) 2021-2024 Aaron Fiore (Founder, Evergreen Crypto LLC)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

#
# 'fetch' module
#

USER root

RUN pacman -Syu \
  composer \
  proxychains-ng \
  --noconfirm --disable-download-timeout

RUN sed -i \
  -e 's:^;extension=bcmath:extension=bcmath:' \
  -e 's:^;extension=gmp:extension=gmp:' \
  -e 's:^;extension=iconv:extension=iconv:' \
  /etc/php/php.ini

# Add builder user for `composer`
RUN useradd -m -s /bin/bash -r builder

USER builder
WORKDIR /usr/local/lib/php

RUN composer require -n ozdemirburak/json-csv
RUN composer require -n ccxt/ccxt

# vim: sw=2 sts=2 si ai et
