# docker-finance | modern accounting for the power-user
#
# Copyright (C) 2021-2025 Aaron Fiore (Founder, Evergreen Crypto LLC)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

#
# 'root' module
#

USER root

# Prevent system upgrades from using Arch's `root` package
RUN sed -i 's:^#IgnorePkg   =:IgnorePkg   = root:' /etc/pacman.conf

# ROOT.cern
# https://hub.docker.com/r/evergreencrypto/root
COPY --from=evergreencrypto/root:archlinux /root/root-*.pkg.tar.zst /usr/local/src/

WORKDIR /usr/local/src
RUN pacman -Syu --noconfirm --disable-download-timeout
RUN pacman -U root-*.pkg.tar.zst --noconfirm --disable-download-timeout

# docker-finance
RUN pacman -Syu \
  benchmark \
  botan \
  crypto++ \
  gtest \
  libsodium \
  --noconfirm --disable-download-timeout

# vim: sw=2 sts=2 si ai et
